---
# Copyright (c) 2015 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# This software contains the intellectual property of Dell Inc. or is licensed to Dell Inc. from third parties.
# Use of this software and the intellectual property contained therein is expressly limited to the terms and
# conditions of the License Agreement under which it is provided by or on behalf of Dell Inc. or its subsidiaries.

kind: pipeline
type: docker
name: copyright-inspect

clone:
  skip_verify: true

trigger:
  branch:
    - master
  event:
    - pull_request
  repo:
    include:
      - vxrail/*

image_pull_secrets:
  - dockerconfig

steps:
  - name: github-init-status
    image: amaas-eos-drm1.cec.lab.emc.com:5033/vxraildevops/github-status
    settings:
      state: pending
      context: continuous-integration/copyright-inspect
      github_api_token:
        from_secret: github_api_token

  - name: inspect
    image: amaas-eos-drm1.cec.lab.emc.com:5033/vxraildevops/poxio/poxio-cli:latest
    commands:
      - poxio copyright inspect --start-commit ${DRONE_COMMIT_BEFORE} --end-commit ${DRONE_COMMIT} .

  - name: github-status-change
    image: amaas-eos-drm1.cec.lab.emc.com:5033/vxraildevops/github-status
    settings:
      context: continuous-integration/copyright-inspect
      github_api_token:
        from_secret: github_api_token
    when:
      status:
        - success
        - failure
    depends_on:
      - inspect
